name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64
    
    outputs:
      image-tag: ${{ steps.tag.outputs.tag }}
      
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: "Generate image tag"
      id: tag
      run: |
        GIT_COMMIT=$(git rev-parse --short=7 HEAD)
        echo "tag=${GIT_COMMIT}" >> $GITHUB_OUTPUT
        echo "platform-tag=${GIT_COMMIT}-${{ matrix.arch }}" >> $GITHUB_OUTPUT
      
    - name: "Login to Docker Hub"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: "Build Docker image"
      run: make docker_image
      env:
        PLATFORM: ${{ matrix.arch }}
        DOCKER_TAG: ${{ steps.tag.outputs.platform-tag }}
        
    - name: "Test Docker image"
      run: make docker_test
      env:
        PLATFORM: ${{ matrix.arch }}
        DOCKER_TAG: ${{ steps.tag.outputs.platform-tag }}
        
    - name: "Push Docker image"
      run: make docker_push
      env:
        PLATFORM: ${{ matrix.arch }}
        DOCKER_TAG: ${{ steps.tag.outputs.platform-tag }}
        
  manifest:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: "Login to Docker Hub"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: "Create and push manifest"
      run: make docker_manifest
      env:
        DOCKER_TAG: ${{ needs.build.outputs.image-tag }}
