name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64
    
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
      
    - name: "Login to Docker Hub"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: "Build and Test Docker Image"
      env:
        PLATFORM: ${{ matrix.arch }}
      run: |
        make docker_image DOCKER_TAG=${{ github.sha }}
        make docker_test

    - name: "Push Docker image"
      env:
        PLATFORM: ${{ matrix.arch }}
      run: make docker_push
